game: ../src/gametest.c ../../main/src/bullet.c ../../main/src/tank.c ../../main/src/map.c ../../main/src/game.c 
	gcc -o game ../src/gametest.c ../../main/src/bullet.c ../../main/src/tank.c ../../main/src/map.c ../../main/src/game.c 
clean :
	rm -f *.o game